feat: channels with messages linked to user
LukeBrandon/leurocord pull request #39
Opened 2023-08-04 21:56 UTC by FlynnOConnell

Addition of channels. 

- Each channel stores a group of messages
- Each message is tied to a user
- If a user is deleted, the message is still stored, with the user_id set to "deleted"

2023-08-04 22:32 UTC, LukeBrandon commented on backend/migrations/20230804194015_add_user_to_message.up.sql
> +ADD CONSTRAINT fk_channel FOREIGN KEY (channel_id) REFERENCES channel(id);
```suggestion
ADD COLUMN user_id NOT NULL FOREIGN KEY (user_id) REFERENCES fluke_user(id),
ADD COLUMN channel_id NOT NULL FOREIGN KEY (channel_id) REFERENCES channel(id);
```
Think you can just do this.

2023-08-04 22:35 UTC, LukeBrandon commented on backend/migrations/20230804194015_add_user_to_message.down.sql
> +DROP CONSTRAINT IF EXISTS fk_channel,
```suggestion
```
If you put constraints on the value directly you can get rid of this

2023-08-04 22:36 UTC, LukeBrandon commented on backend/src/models/message.rs
> +    pub user_id: i64,
you need to update the message create to include the channel message

2023-08-04 22:48 UTC, LukeBrandon commented on backend/migrations/20230804194015_add_user_to_message.down.sql
> +DROP CONSTRAINT IF EXISTS fk_channel,
The constraint applies to the column, should just be able to drop column?

2023-08-04 22:49 UTC, LukeBrandon commented on backend/migrations/20230804194015_add_user_to_message.up.sql
> +ADD CONSTRAINT fk_channel FOREIGN KEY (channel_id) REFERENCES channel(id);
```suggestion
ADD CONSTRAINT FOREIGN KEY (user_id) REFERENCES fluke_user(id),
ADD CONSTRAINT FOREIGN KEY (channel_id) REFERENCES channel(id);
```
you dont need to have these names do you?

2023-08-06 02:02 UTC, LukeBrandon commented on backend/src/models/user.rs
> +    pub deleted: Option<bool>,
```suggestion
    pub deleted: bool,
```

2023-08-06 02:03 UTC, LukeBrandon commented on backend/src/main.rs
> +            "/channel/:id",
```suggestion
            "/channels/:id",
```

2023-08-06 02:06 UTC, LukeBrandon commented on backend/src/controllers/user.rs
> +    .await;
This won't work, `user_id` isn't nullable.  I would just do a soft delete on the user model and update them to be `deleted=true` so you don't need to mess with cascading for now.  Then your `list` will have to filter out the deleted ones.

2023-08-06 02:08 UTC, LukeBrandon commented on backend/src/controllers/channel.rs
> +    let channel: ChannelModel = sqlx::query_as::<_, ChannelModel>(sql)
use `sqlx::query_as!` macro

2023-08-06 02:09 UTC, LukeBrandon commented on backend/src/controllers/user.rs
> +    .await;
```suggestion
```
Actually you already added a deleted, I'd just remove this then

2023-08-06 02:11 UTC, LukeBrandon commented on backend/migrations/20230804194015_add_user_to_message.down.sql
> +DROP CONSTRAINT IF EXISTS fk_channel,
you dont need to drop the constraints if you're dropping the column

2023-08-06 02:13 UTC, LukeBrandon requested changes
few things

2023-08-06 22:57 UTC, LukeBrandon commented on backend/src/controllers/message.rs
> +        "UPDATE message SET message=$1 WHERE id=$2 RETURNING id, message, created_at, user_id, channel_id",
```suggestion
        "UPDATE message SET message=$1 WHERE id=$2 RETURNING *",
```

2023-08-06 22:58 UTC, LukeBrandon commented on backend/src/controllers/message.rs
> +        &message.message
dis broken

2023-08-06 22:58 UTC, LukeBrandon commented on backend/src/controllers/user.rs
> +    Ok((StatusCode::OK, Json(json!({"message": "User soft-deleted", "user_id": id.to_string()}))))
```suggestion
    Ok((StatusCode::OK, Json(json!({"message": "User deleted", "user_id": id.to_string()}))))
```
They don't need to know its soft

2023-08-07 13:09 UTC, LukeBrandon commented on backend/src/controllers/message.rs
> +        &message.message
you need to add `user_id` and `channel_id` here

2023-08-07 15:59 UTC, FlynnOConnell reviewed
Fixed multiple issues

2023-08-07 16:32 UTC, LukeBrandon requested changes
Gotta run `cargo sqlx prepare`

2023-08-07 18:32 UTC, LukeBrandon approved these changes

2023-08-07 18:32 UTC, merged